---
title: "Google Colab & Rstudio Cloud"
#subtitle: "Soluções Plug and Play"
author: 
  - name: Ana Clara  
  - name: Gabriela Monteiro  
  - name: Lucas Loureiro  
  - name: Rafael Ramos  
  - name: Vinicius Paiva
# title-slide-attributes:
#     data-background-image: "/path/to/image"
#     data-background-size: contain
#     data-background-opacity: "0.45"
highlight-style: pygments
format: 
  revealjs:
    theme: [night]
    slide-number: true
    chalkboard:
      buttons: true
    preview-links: auto
    css: www/style.css
    logo: www/logo-UnB.png
    footer: <http://gmail.com> 
editor: source
---

## Início

::: columns
::: {.column width="50%"}
[Rstudio Cloud](https://rstudio.cloud/)
:::

::: {.column width="50%"}
[Google Colab](https://colab.research.google.com/)
:::
:::

<b> Qual escolher? </b>

## Tech

* Docker
* Rstudio
* Jupyterlab
* Windows Subsystem for Linux

## Docker

Apresentar o DOCKER!!!!!

## Estrutura do Rstudio Cloud

## Rstudio Cloud

::: columns
::: {.column width="50%"}
#### Vantagens  
-   No feed/subscription;
-   Public web service (RStudio IDE);
-   Compartilhamento
-   Allow multipĺe projects;
-   Persistence;
:::

::: {.column width="50%"}
#### Desvantagens
-   Restrição física da máquina (RAM, CPU, HDD);
-   Restrição mensal de workload (horas/projeto);
-   Escalonamento;
:::
:::

## Mitigando os "problemas" - Rstudio Cloud

## Estrutura do Google Colab

## Google Colab

::: columns 
::: {.column width="50%"}
### Vantagens
-   No feed/subscription; 
-   Public web service (Jupyterlab IDE); 
-   Compartilhamento; 
-   Suporte a GPU (plano pago); 
-   Python & R kernels;
:::

::: {.column width="50%"}
#### Desvantagens
-   Persitência (dados e pacotes)
-   Restrição física
-   Escalonamento
:::
:::

## Google Colab e seus kernels

Podemos optar pela linguagem de programação que iremos usar no jupyterlab na sessão destinada ao runtime (kernel)


## Mitigando os "problemas" - Google Colab

-   Plano pago
-   Persistência (via mount do google Drive)
-   

## Solução Customizada????

## Solução Customizada - Pequena/Média Escala

Vamos dar deploy em uma solução customizada usando docker como base para um Rstudio Server!!!!

Pre-requesitos:  
-   Computador com uma configuração razoável (RAM, CPU);  
-   Conexão estável com a internet e segura;  
-   Energia;  

Vantagens:  
-   Web service    
-   Configuração do "server" mais robusta  
-   Free!!!!!!!!!!  

Desvantagem:  
-   "Custo" de manutenção;  
-   Curva de aprendizado (bem suavel!!!!!!)
-   Atualização e manutenção das imagens dos conteiners;
-   Sistema unificado (todos os usuários no mesmo conteiner)

## Deploy Rstudio Server

## Solução Customizada - Pequena/Média Escala

Ilustrando agora uma solução customizada usando docker e jupyterlab
(Apenas mostrar funcionando, deploy bastante complexo...)